'use client'

import Link from 'next/link'
import { Button } from '@/components/ui/button'
import {
  ArrowRight,
  Code2,
  Zap,
  Globe,
  Upload,
  FileText,
  LogOut,
  User,
  Smartphone,
  GraduationCap,
  Rocket,
  BookOpen,
  Users,
  FileCode,
  Presentation,
  MessageSquare,
  Play,
  Download,
  Wrench,
  Bot,
  Layers,
  CheckCircle,
  Star,
  Building,
  Sparkles,
  Monitor,
  Database,
  Cloud,
  Shield,
  Clock,
  Cpu,
  GitBranch
} from 'lucide-react'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useWorkspaceStore } from '@/store/workspaceStore'
import { useAuth } from '@/hooks/useAuth'

export default function Home() {
  const { createWorkspaceWithProject } = useWorkspaceStore()
  const { isAuthenticated, isLoading, checkAuth, user, logout } = useAuth()
  const router = useRouter()
  const [placeholderIndex, setPlaceholderIndex] = useState(0)
  const [demoStep, setDemoStep] = useState(0)
  const [demoCode, setDemoCode] = useState('')
  const [isTyping, setIsTyping] = useState(false)
  const placeholders = [
    'Build a React dashboard with TypeScript and Tailwind CSS',
    'Create a Flutter mobile app with Firebase backend',
    'Develop a full-stack Next.js app with authentication',
    'Build a Python FastAPI with PostgreSQL database',
    'Create an e-commerce platform with payment integration',
    'Develop a Django web app with user authentication',
    'Build a hospital management system',
    'Create a microservices architecture with Docker'
  ]

  useEffect(() => {
    const interval = setInterval(() => {
      setPlaceholderIndex((prev) => (prev + 1) % placeholders.length)
    }, 3000)
    return () => clearInterval(interval)
  }, [])

  // Demo animation effect
  const demoSteps = [
    { title: 'Describe Your Idea', agent: 'You', status: 'active' },
    { title: 'AI Analyzes Requirements', agent: 'Planner Agent', status: 'pending' },
    { title: 'Generating Code...', agent: 'Coder Agent', status: 'pending' },
    { title: 'Running Tests', agent: 'Fixer Agent', status: 'pending' },
    { title: 'Project Ready!', agent: 'Complete', status: 'pending' }
  ]

  const sampleCode = `// Generated by BharatBuild AI
import React from 'react';
import { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <h1>Welcome to My App</h1>
      <button onClick={() => setCount(c => c + 1)}>
        Count: {count}
      </button>
    </div>
  );
}`

  useEffect(() => {
    // Auto-advance demo steps
    const stepInterval = setInterval(() => {
      setDemoStep((prev) => (prev + 1) % 5)
    }, 2500)

    return () => clearInterval(stepInterval)
  }, [])

  useEffect(() => {
    // Typing animation for code
    if (demoStep === 2) {
      setIsTyping(true)
      let currentIndex = 0
      setDemoCode('')
      const typingInterval = setInterval(() => {
        if (currentIndex < sampleCode.length) {
          setDemoCode(sampleCode.slice(0, currentIndex + 1))
          currentIndex++
        } else {
          clearInterval(typingInterval)
          setIsTyping(false)
        }
      }, 15)
      return () => clearInterval(typingInterval)
    }
  }, [demoStep])

  const handlePromptSubmit = (prompt: string) => {
    if (!prompt.trim()) return

    if (!checkAuth()) {
      sessionStorage.setItem('pendingPrompt', prompt)
      sessionStorage.setItem('redirectAfterLogin', '/build')
      router.push('/login')
      return
    }

    const projectName = prompt.length > 50 ? prompt.substring(0, 50) + '...' : prompt
    const { workspace, project } = createWorkspaceWithProject(
      `Workspace ${new Date().toLocaleDateString()}`,
      projectName,
      prompt
    )
    sessionStorage.setItem('initialPrompt', prompt)
    sessionStorage.setItem('workspaceId', workspace.id)
    sessionStorage.setItem('projectId', project.id)
    router.push('/build')
  }

  return (
    <div className="min-h-screen bg-[hsl(var(--bolt-bg-primary))] relative overflow-hidden">
      {/* Gradient background effect */}
      <div className="absolute inset-0 bg-gradient-to-br from-blue-500/5 via-transparent to-cyan-500/5" />

      {/* Header */}
      <header className="relative z-10 border-b border-[hsl(var(--bolt-border))]">
        <div className="container mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
              <Zap className="w-5 h-5 text-white" />
            </div>
            <span className="font-bold text-xl text-[hsl(var(--bolt-text-primary))]">BharatBuild</span>
            <span className="text-xs px-2 py-0.5 rounded-full bg-gradient-to-r from-orange-500 to-green-500 text-white font-medium">AI</span>
          </Link>

          <nav className="hidden md:flex items-center gap-8">
            <Link href="/projects" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))] transition-colors">
              My Projects
            </Link>
            <Link href="/build" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))] transition-colors">
              Build
            </Link>
            <Link href="/paper" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))] transition-colors">
              Research Paper
            </Link>
            <Link href="/campus-drive" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))] transition-colors">
              Campus Drive
            </Link>
            <Link href="/lab" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))] transition-colors">
              Lab Practice
            </Link>
            <Link href="/pricing" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))] transition-colors">
              Pricing
            </Link>
          </nav>

          <div className="flex items-center gap-4">
            {isAuthenticated ? (
              <>
                <Link
                  href="/profile"
                  className="hidden sm:flex items-center gap-2 px-3 py-1.5 rounded-lg bg-[hsl(var(--bolt-bg-tertiary))] border border-[hsl(var(--bolt-border))] hover:bg-[hsl(var(--bolt-bg-quaternary))] transition-colors"
                  title="Edit Profile"
                >
                  <User className="w-4 h-4 text-[hsl(var(--bolt-accent))]" />
                  <span className="text-sm text-[hsl(var(--bolt-text-primary))]">
                    {user?.name || user?.email?.split('@')[0] || 'User'}
                  </span>
                </Link>
                <Link href="/build">
                  <Button className="bolt-gradient hover:opacity-90 transition-opacity">
                    Go to Build
                  </Button>
                </Link>
                <button
                  onClick={logout}
                  className="flex items-center gap-2 px-3 py-2 rounded-lg text-[hsl(var(--bolt-text-secondary))] hover:text-red-400 hover:bg-red-500/10 transition-colors"
                  title="Logout"
                >
                  <LogOut className="w-4 h-4" />
                  <span className="hidden sm:inline text-sm">Logout</span>
                </button>
              </>
            ) : (
              <>
                <Link href="/login">
                  <Button variant="ghost" className="text-[hsl(var(--bolt-text-secondary))] hover:text-[hsl(var(--bolt-text-primary))]">
                    Sign In
                  </Button>
                </Link>
                <Link href="/register">
                  <Button className="bolt-gradient hover:opacity-90 transition-opacity">
                    Get Started Free
                  </Button>
                </Link>
              </>
            )}
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <main className="relative z-10">
        <div className="container mx-auto px-6 py-16 md:py-24">
          <div className="text-center max-w-5xl mx-auto">
            {/* Badge */}
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-gradient-to-r from-orange-500/10 to-green-500/10 border border-orange-500/20 mb-6">
              <span className="text-2xl">🇮🇳</span>
              <span className="text-sm font-medium text-orange-400">India's #1 AI Development Platform</span>
            </div>

            {/* Main Heading */}
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 text-[hsl(var(--bolt-text-primary))]">
              Build <span className="bolt-gradient-text">Full-Stack Apps</span> with AI
            </h1>

            {/* Subheading */}
            <p className="text-lg md:text-xl text-[hsl(var(--bolt-text-secondary))] mb-8 max-w-3xl mx-auto">
              From web apps to mobile apps, academic projects to production systems -
              describe what you want and watch AI build it in real-time
            </p>

            {/* Prompt Input */}
            <div className="max-w-3xl mx-auto mb-6">
              <div className="group relative">
                <div className="absolute -inset-1 bg-gradient-to-r from-blue-500 to-cyan-500 rounded-2xl blur opacity-20 group-hover:opacity-40 transition duration-200"></div>
                <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border-2 border-[hsl(var(--bolt-border))] rounded-2xl p-2 hover:border-[hsl(var(--bolt-accent))] transition-all">
                  <form onSubmit={(e) => {
                    e.preventDefault()
                    const input = e.currentTarget.querySelector('input') as HTMLInputElement
                    const prompt = input.value.trim()
                    if (prompt) {
                      handlePromptSubmit(prompt)
                    }
                  }}>
                    <div className="flex items-center gap-2">
                      <input
                        type="text"
                        placeholder={placeholders[placeholderIndex]}
                        className="flex-1 bg-transparent border-none outline-none text-[hsl(var(--bolt-text-primary))] placeholder:text-[hsl(var(--bolt-text-secondary))] px-4 py-3 text-base transition-all duration-500"
                      />
                      <Button type="submit" className="bolt-gradient hover:opacity-90 transition-opacity px-6 py-3">
                        Build Now
                        <ArrowRight className="ml-2 w-4 h-4" />
                      </Button>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            {/* Quick Examples */}
            <div className="flex flex-wrap gap-2 justify-center mb-8">
              {[
                { prompt: 'Build a Flutter mobile app with Firebase', label: '📱 Flutter App', color: 'from-blue-500/20 to-cyan-500/20' },
                { prompt: 'Create an e-commerce website with React', label: '🛍️ E-commerce', color: 'from-purple-500/20 to-pink-500/20' },
                { prompt: 'Build an analytics dashboard with charts', label: '📊 Dashboard', color: 'from-green-500/20 to-emerald-500/20' },
                { prompt: 'Create a hospital management system', label: '🏥 HMS', color: 'from-orange-500/20 to-red-500/20' },
                { prompt: 'Build a REST API with Node.js', label: '⚡ API', color: 'from-yellow-500/20 to-orange-500/20' }
              ].map((example, idx) => (
                <button
                  key={idx}
                  onClick={() => handlePromptSubmit(example.prompt)}
                  className={`text-sm px-4 py-2 rounded-full bg-gradient-to-r ${example.color} border border-[hsl(var(--bolt-border))] text-[hsl(var(--bolt-text-secondary))] hover:border-[hsl(var(--bolt-accent))] hover:text-[hsl(var(--bolt-text-primary))] transition-all`}
                >
                  {example.label}
                </button>
              ))}
            </div>

            {/* Stats */}
            <div className="flex flex-wrap justify-center gap-8 mb-12">
              {[
                { value: '50+', label: 'Tech Stacks' },
                { value: '10K+', label: 'Projects Built' },
                { value: '4', label: 'Build Modes' },
                { value: '< 2min', label: 'Avg Build Time' }
              ].map((stat, i) => (
                <div key={i} className="text-center">
                  <div className="text-2xl md:text-3xl font-bold bolt-gradient-text">{stat.value}</div>
                  <div className="text-sm text-[hsl(var(--bolt-text-secondary))]">{stat.label}</div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* How It Works - Live Demo Section */}
        <div className="container mx-auto px-6 py-16 bg-[hsl(var(--bolt-bg-secondary))]/50">
          <div className="text-center mb-12">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 mb-4">
              <Play className="w-4 h-4 text-purple-500" />
              <span className="text-sm font-medium text-purple-400">Live Demo</span>
            </div>
            <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
              See How It Works
            </h2>
            <p className="text-lg text-[hsl(var(--bolt-text-secondary))] max-w-2xl mx-auto">
              Watch AI agents build your project in real-time - from idea to working code
            </p>
          </div>

          <div className="max-w-6xl mx-auto">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-start">
              {/* Step Progress */}
              <div className="space-y-4">
                {[
                  { step: 0, title: 'Describe Your Idea', desc: 'Enter what you want to build in plain English', icon: MessageSquare, agent: 'You' },
                  { step: 1, title: 'AI Analyzes Requirements', desc: 'Planner agent breaks down your project into tasks', icon: Bot, agent: 'Planner Agent' },
                  { step: 2, title: 'Code Generation', desc: 'Coder agent writes clean, production-ready code', icon: Code2, agent: 'Coder Agent' },
                  { step: 3, title: 'Testing & Fixing', desc: 'Fixer agent runs tests and fixes any errors', icon: Wrench, agent: 'Fixer Agent' },
                  { step: 4, title: 'Project Ready!', desc: 'Download ZIP, APK, or deploy to cloud', icon: CheckCircle, agent: 'Complete' }
                ].map((item, i) => (
                  <div
                    key={i}
                    className={`flex items-start gap-4 p-4 rounded-xl transition-all duration-500 ${
                      demoStep === item.step
                        ? 'bg-gradient-to-r from-blue-500/20 to-purple-500/20 border border-blue-500/30'
                        : demoStep > item.step
                        ? 'bg-green-500/10 border border-green-500/20'
                        : 'bg-[hsl(var(--bolt-bg-tertiary))] border border-transparent'
                    }`}
                  >
                    <div className={`w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0 transition-all ${
                      demoStep === item.step
                        ? 'bg-gradient-to-br from-blue-500 to-purple-500'
                        : demoStep > item.step
                        ? 'bg-green-500'
                        : 'bg-[hsl(var(--bolt-bg-quaternary))]'
                    }`}>
                      {demoStep > item.step ? (
                        <CheckCircle className="w-5 h-5 text-white" />
                      ) : (
                        <item.icon className={`w-5 h-5 ${demoStep === item.step ? 'text-white' : 'text-[hsl(var(--bolt-text-secondary))]'}`} />
                      )}
                    </div>
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h4 className={`font-semibold ${
                          demoStep >= item.step ? 'text-[hsl(var(--bolt-text-primary))]' : 'text-[hsl(var(--bolt-text-secondary))]'
                        }`}>
                          {item.title}
                        </h4>
                        {demoStep === item.step && (
                          <span className="px-2 py-0.5 rounded-full bg-blue-500/20 text-blue-400 text-xs animate-pulse">
                            In Progress
                          </span>
                        )}
                      </div>
                      <p className="text-sm text-[hsl(var(--bolt-text-secondary))]">{item.desc}</p>
                      <span className="text-xs text-[hsl(var(--bolt-accent))] mt-1 inline-block">{item.agent}</span>
                    </div>
                  </div>
                ))}
              </div>

              {/* Code Preview Window */}
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-purple-500/20 rounded-3xl blur-2xl" />
                <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl overflow-hidden">
                  {/* IDE Header */}
                  <div className="flex items-center justify-between px-4 py-3 border-b border-[hsl(var(--bolt-border))] bg-[hsl(var(--bolt-bg-tertiary))]">
                    <div className="flex items-center gap-2">
                      <div className="flex gap-1.5">
                        <div className="w-3 h-3 rounded-full bg-red-500" />
                        <div className="w-3 h-3 rounded-full bg-yellow-500" />
                        <div className="w-3 h-3 rounded-full bg-green-500" />
                      </div>
                      <span className="text-sm text-[hsl(var(--bolt-text-secondary))] ml-2">App.tsx</span>
                    </div>
                    <div className="flex items-center gap-2">
                      {demoStep >= 2 && (
                        <span className={`text-xs px-2 py-1 rounded ${
                          demoStep === 2 ? 'bg-blue-500/20 text-blue-400 animate-pulse' : 'bg-green-500/20 text-green-400'
                        }`}>
                          {demoStep === 2 ? 'Writing...' : 'Complete'}
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Code Area */}
                  <div className="p-4 h-[400px] overflow-hidden font-mono text-sm">
                    {demoStep < 2 ? (
                      <div className="flex flex-col items-center justify-center h-full text-center">
                        <Bot className={`w-16 h-16 mb-4 ${demoStep === 1 ? 'text-blue-500 animate-pulse' : 'text-[hsl(var(--bolt-text-secondary))]'}`} />
                        <p className="text-[hsl(var(--bolt-text-secondary))]">
                          {demoStep === 0 ? 'Waiting for your prompt...' : 'Analyzing requirements...'}
                        </p>
                        {demoStep === 1 && (
                          <div className="mt-4 flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full bg-blue-500 animate-bounce" style={{ animationDelay: '0ms' }} />
                            <div className="w-2 h-2 rounded-full bg-blue-500 animate-bounce" style={{ animationDelay: '150ms' }} />
                            <div className="w-2 h-2 rounded-full bg-blue-500 animate-bounce" style={{ animationDelay: '300ms' }} />
                          </div>
                        )}
                      </div>
                    ) : (
                      <pre className="text-[hsl(var(--bolt-text-primary))] whitespace-pre-wrap">
                        <code>
                          {demoStep === 2 ? demoCode : sampleCode}
                          {demoStep === 2 && isTyping && <span className="inline-block w-2 h-4 bg-blue-500 animate-pulse ml-0.5" />}
                        </code>
                      </pre>
                    )}
                  </div>

                  {/* Terminal Area */}
                  {demoStep >= 3 && (
                    <div className="border-t border-[hsl(var(--bolt-border))] bg-black/50 p-3">
                      <div className="flex items-center gap-2 mb-2">
                        <span className="text-xs text-gray-500">Terminal</span>
                      </div>
                      <div className="font-mono text-xs space-y-1">
                        {demoStep >= 3 && (
                          <p className="text-green-400">$ npm run build</p>
                        )}
                        {demoStep >= 3 && (
                          <p className="text-gray-400">Compiling...</p>
                        )}
                        {demoStep >= 4 && (
                          <>
                            <p className="text-green-400">✓ Build completed successfully!</p>
                            <p className="text-cyan-400">✓ All tests passed (12/12)</p>
                            <p className="text-yellow-400">📦 Project ready for download</p>
                          </>
                        )}
                      </div>
                    </div>
                  )}
                </div>

                {/* Download Buttons - Show when complete */}
                {demoStep === 4 && (
                  <div className="mt-4 flex gap-3 justify-center">
                    <Button size="sm" className="bolt-gradient" onClick={() => router.push('/build')}>
                      <Play className="w-4 h-4 mr-2" /> Try It Now
                    </Button>
                    <Button size="sm" variant="outline">
                      <Download className="w-4 h-4 mr-2" /> Download ZIP
                    </Button>
                  </div>
                )}
              </div>
            </div>

            {/* Agent Pills */}
            <div className="mt-12 text-center">
              <p className="text-sm text-[hsl(var(--bolt-text-secondary))] mb-4">Powered by 8 Specialized AI Agents</p>
              <div className="flex flex-wrap justify-center gap-2">
                {['Planner', 'Coder', 'Fixer', 'Tester', 'Documenter', 'Designer', 'Reviewer', 'Deployer'].map((agent, i) => (
                  <span
                    key={i}
                    className="px-3 py-1.5 rounded-full bg-[hsl(var(--bolt-bg-tertiary))] border border-[hsl(var(--bolt-border))] text-xs text-[hsl(var(--bolt-text-secondary))] flex items-center gap-1.5"
                  >
                    <Bot className="w-3 h-3" />
                    {agent}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </div>

        {/* 4 Project Modes Section */}
        <div className="container mx-auto px-6 py-16 bg-[hsl(var(--bolt-bg-secondary))]/50">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
              4 Powerful Build Modes
            </h2>
            <p className="text-lg text-[hsl(var(--bolt-text-secondary))] max-w-2xl mx-auto">
              Choose the mode that fits your needs - each optimized for different use cases
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-7xl mx-auto">
            {/* Student Mode */}
            <div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-all" />
              <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-6 hover:border-blue-500/50 transition-all h-full">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center mb-4">
                  <GraduationCap className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-[hsl(var(--bolt-text-primary))] mb-2">Student Mode</h3>
                <p className="text-[hsl(var(--bolt-text-secondary))] text-sm mb-4">
                  Complete academic projects with all documentation
                </p>
                <ul className="space-y-2 text-sm text-[hsl(var(--bolt-text-secondary))]">
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Full Source Code</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> SRS Document</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Project Report</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> PPT Presentation</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Viva Q&A</li>
                </ul>
              </div>
            </div>

            {/* Developer Mode */}
            <div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-br from-green-500/20 to-emerald-500/20 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-all" />
              <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-6 hover:border-green-500/50 transition-all h-full">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-green-500 to-emerald-500 flex items-center justify-center mb-4">
                  <Code2 className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-[hsl(var(--bolt-text-primary))] mb-2">Developer Mode</h3>
                <p className="text-[hsl(var(--bolt-text-secondary))] text-sm mb-4">
                  Production-ready code like Bolt.new
                </p>
                <ul className="space-y-2 text-sm text-[hsl(var(--bolt-text-secondary))]">
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Clean Architecture</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Best Practices</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Live Preview</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Auto-fixer Agent</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Export & Deploy</li>
                </ul>
              </div>
            </div>

            {/* Founder Mode */}
            <div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-all" />
              <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-6 hover:border-purple-500/50 transition-all h-full">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center mb-4">
                  <Rocket className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-[hsl(var(--bolt-text-primary))] mb-2">Founder Mode</h3>
                <p className="text-[hsl(var(--bolt-text-secondary))] text-sm mb-4">
                  Build MVPs with business planning
                </p>
                <ul className="space-y-2 text-sm text-[hsl(var(--bolt-text-secondary))]">
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> PRD Document</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Business Plan</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> MVP Code</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Pitch Deck</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Roadmap</li>
                </ul>
              </div>
            </div>

            {/* College Mode */}
            <div className="group relative">
              <div className="absolute inset-0 bg-gradient-to-br from-orange-500/20 to-red-500/20 rounded-2xl blur-xl opacity-0 group-hover:opacity-100 transition-all" />
              <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-6 hover:border-orange-500/50 transition-all h-full">
                <div className="w-12 h-12 rounded-xl bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center mb-4">
                  <Building className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-[hsl(var(--bolt-text-primary))] mb-2">College Mode</h3>
                <p className="text-[hsl(var(--bolt-text-secondary))] text-sm mb-4">
                  For institutions & batch management
                </p>
                <ul className="space-y-2 text-sm text-[hsl(var(--bolt-text-secondary))]">
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Batch Management</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Faculty Dashboard</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Campus Drive</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Quiz System</li>
                  <li className="flex items-center gap-2"><CheckCircle className="w-4 h-4 text-green-500" /> Analytics</li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        {/* Mobile App Generation Section */}
        <div className="container mx-auto px-6 py-16">
          <div className="max-w-6xl mx-auto">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-green-500/10 border border-green-500/20 mb-4">
                  <Smartphone className="w-4 h-4 text-green-500" />
                  <span className="text-sm font-medium text-green-400">Mobile App Generation</span>
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
                  Build Mobile Apps with <span className="text-blue-400">Flutter</span>
                </h2>
                <p className="text-lg text-[hsl(var(--bolt-text-secondary))] mb-6">
                  Generate cross-platform mobile apps for Android and iOS. Download APK directly or export the full Flutter project.
                </p>
                <ul className="space-y-3 mb-8">
                  {[
                    'Flutter & Dart code generation',
                    'Direct APK download for Android',
                    'Firebase integration ready',
                    'React Native support',
                    'Expo for quick prototypes'
                  ].map((item, i) => (
                    <li key={i} className="flex items-center gap-3 text-[hsl(var(--bolt-text-secondary))]">
                      <CheckCircle className="w-5 h-5 text-green-500 flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
                <Button onClick={() => handlePromptSubmit('Build a Flutter mobile app with Firebase authentication')} className="bolt-gradient">
                  Try Flutter App
                  <Smartphone className="ml-2 w-4 h-4" />
                </Button>
              </div>
              <div className="relative">
                <div className="absolute inset-0 bg-gradient-to-br from-blue-500/20 to-cyan-500/20 rounded-3xl blur-2xl" />
                <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-8">
                  <div className="flex items-center gap-4 mb-6">
                    <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
                      <Smartphone className="w-8 h-8 text-white" />
                    </div>
                    <div>
                      <h3 className="text-xl font-semibold text-[hsl(var(--bolt-text-primary))]">my_flutter_app</h3>
                      <p className="text-sm text-[hsl(var(--bolt-text-secondary))]">Flutter • Dart • Firebase</p>
                    </div>
                  </div>
                  <div className="space-y-3">
                    <div className="flex items-center justify-between p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg">
                      <span className="text-sm text-[hsl(var(--bolt-text-secondary))]">app-release.apk</span>
                      <Button size="sm" variant="outline" className="text-green-400 border-green-500/30 hover:bg-green-500/10">
                        <Download className="w-4 h-4 mr-1" /> APK
                      </Button>
                    </div>
                    <div className="flex items-center justify-between p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg">
                      <span className="text-sm text-[hsl(var(--bolt-text-secondary))]">Full Project ZIP</span>
                      <Button size="sm" variant="outline">
                        <Download className="w-4 h-4 mr-1" /> ZIP
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Document Generation Section */}
        <div className="container mx-auto px-6 py-16 bg-[hsl(var(--bolt-bg-secondary))]/50">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
              Auto-Generated Documentation
            </h2>
            <p className="text-lg text-[hsl(var(--bolt-text-secondary))] max-w-2xl mx-auto">
              Get professional documents alongside your code - perfect for academic submissions
            </p>
          </div>

          <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4 max-w-5xl mx-auto">
            {[
              { icon: FileText, label: 'SRS Document', color: 'from-blue-500 to-blue-600' },
              { icon: FileCode, label: 'Source Code', color: 'from-green-500 to-green-600' },
              { icon: BookOpen, label: 'Project Report', color: 'from-purple-500 to-purple-600' },
              { icon: Presentation, label: 'PPT Slides', color: 'from-orange-500 to-orange-600' },
              { icon: MessageSquare, label: 'Viva Q&A', color: 'from-pink-500 to-pink-600' },
              { icon: FileText, label: 'Research Paper', color: 'from-cyan-500 to-cyan-600' }
            ].map((doc, i) => (
              <div key={i} className="bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-xl p-4 text-center hover:border-[hsl(var(--bolt-accent))] transition-all">
                <div className={`w-12 h-12 rounded-lg bg-gradient-to-br ${doc.color} flex items-center justify-center mx-auto mb-3`}>
                  <doc.icon className="w-6 h-6 text-white" />
                </div>
                <span className="text-sm font-medium text-[hsl(var(--bolt-text-primary))]">{doc.label}</span>
              </div>
            ))}
          </div>
        </div>

        {/* Tech Stack Section */}
        <div className="container mx-auto px-6 py-16">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
              50+ Supported Technologies
            </h2>
            <p className="text-lg text-[hsl(var(--bolt-text-secondary))] max-w-2xl mx-auto">
              Build with any tech stack - we support all major frameworks and languages
            </p>
          </div>

          <div className="flex flex-wrap justify-center gap-3 max-w-4xl mx-auto">
            {[
              'React', 'Next.js', 'Vue.js', 'Angular', 'Svelte',
              'Node.js', 'Express', 'FastAPI', 'Django', 'Flask',
              'Flutter', 'React Native', 'Expo',
              'TypeScript', 'Python', 'Java', 'Go', 'Rust',
              'PostgreSQL', 'MongoDB', 'MySQL', 'Redis', 'Firebase',
              'Docker', 'Kubernetes', 'AWS', 'Tailwind CSS', 'GraphQL'
            ].map((tech, i) => (
              <span
                key={i}
                className="px-4 py-2 rounded-full bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] text-sm text-[hsl(var(--bolt-text-secondary))] hover:border-[hsl(var(--bolt-accent))] hover:text-[hsl(var(--bolt-text-primary))] transition-all"
              >
                {tech}
              </span>
            ))}
          </div>
        </div>

        {/* Features Grid */}
        <div className="container mx-auto px-6 py-16 bg-[hsl(var(--bolt-bg-secondary))]/50">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
              Powerful Features
            </h2>
            <p className="text-lg text-[hsl(var(--bolt-text-secondary))] max-w-2xl mx-auto">
              Everything you need to build, test, and deploy applications
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
            {[
              { icon: Play, title: 'Live Preview', desc: 'See your app running in real-time as code is generated', color: 'text-green-500' },
              { icon: Bot, title: 'Multi-Agent AI', desc: '8 specialized AI agents working together on your project', color: 'text-blue-500' },
              { icon: Wrench, title: 'Auto-Fixer', desc: 'AI automatically fixes errors and improves code quality', color: 'text-orange-500' },
              { icon: GitBranch, title: 'Version Control', desc: 'Built-in undo/redo and version history', color: 'text-purple-500' },
              { icon: Upload, title: 'Import Projects', desc: 'Import existing projects for analysis and enhancement', color: 'text-pink-500' },
              { icon: Download, title: 'Export Anywhere', desc: 'Download ZIP, APK, or deploy to cloud platforms', color: 'text-cyan-500' },
              { icon: Monitor, title: 'Code Editor', desc: 'Full-featured Monaco editor with IntelliSense', color: 'text-yellow-500' },
              { icon: Database, title: 'Database Ready', desc: 'PostgreSQL, MongoDB, Firebase - all supported', color: 'text-red-500' },
              { icon: Shield, title: 'Secure Code', desc: 'Best practices and security built-in', color: 'text-emerald-500' }
            ].map((feature, i) => (
              <div key={i} className="bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-xl p-6 hover:border-[hsl(var(--bolt-accent))] transition-all">
                <feature.icon className={`w-8 h-8 ${feature.color} mb-4`} />
                <h3 className="text-lg font-semibold text-[hsl(var(--bolt-text-primary))] mb-2">{feature.title}</h3>
                <p className="text-sm text-[hsl(var(--bolt-text-secondary))]">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Campus Drive Section */}
        <div className="container mx-auto px-6 py-16">
          <div className="max-w-6xl mx-auto">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div className="order-2 lg:order-1">
                <div className="relative">
                  <div className="absolute inset-0 bg-gradient-to-br from-orange-500/20 to-red-500/20 rounded-3xl blur-2xl" />
                  <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-6">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between p-4 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-blue-500/20 flex items-center justify-center">
                            <Users className="w-5 h-5 text-blue-500" />
                          </div>
                          <div>
                            <p className="font-medium text-[hsl(var(--bolt-text-primary))]">500+ Students</p>
                            <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">Registered for drive</p>
                          </div>
                        </div>
                        <span className="px-3 py-1 rounded-full bg-green-500/20 text-green-400 text-sm">Active</span>
                      </div>
                      <div className="grid grid-cols-3 gap-3">
                        <div className="p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg text-center">
                          <p className="text-2xl font-bold text-[hsl(var(--bolt-text-primary))]">85%</p>
                          <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">Pass Rate</p>
                        </div>
                        <div className="p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg text-center">
                          <p className="text-2xl font-bold text-[hsl(var(--bolt-text-primary))]">50</p>
                          <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">Questions</p>
                        </div>
                        <div className="p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg text-center">
                          <p className="text-2xl font-bold text-[hsl(var(--bolt-text-primary))]">30m</p>
                          <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">Duration</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="order-1 lg:order-2">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-500/10 border border-orange-500/20 mb-4">
                  <Building className="w-4 h-4 text-orange-500" />
                  <span className="text-sm font-medium text-orange-400">For Colleges</span>
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
                  Campus Drive Platform
                </h2>
                <p className="text-lg text-[hsl(var(--bolt-text-secondary))] mb-6">
                  Conduct placement drives with automated quiz system, student registration, and real-time analytics.
                </p>
                <ul className="space-y-3 mb-8">
                  {[
                    'Student self-registration portal',
                    'MCQ & Coding quiz with auto-evaluation',
                    'Real-time leaderboard & analytics',
                    'Bulk result export',
                    'Anti-cheating measures'
                  ].map((item, i) => (
                    <li key={i} className="flex items-center gap-3 text-[hsl(var(--bolt-text-secondary))]">
                      <CheckCircle className="w-5 h-5 text-orange-500 flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
                <Link href="/campus-drive">
                  <Button className="bg-gradient-to-r from-orange-500 to-red-500 hover:opacity-90">
                    Explore Campus Drive
                    <ArrowRight className="ml-2 w-4 h-4" />
                  </Button>
                </Link>
              </div>
            </div>
          </div>
        </div>

        {/* Lab Practice Section */}
        <div className="container mx-auto px-6 py-16 bg-[hsl(var(--bolt-bg-secondary))]/50">
          <div className="max-w-6xl mx-auto">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
              <div>
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-cyan-500/10 border border-cyan-500/20 mb-4">
                  <BookOpen className="w-4 h-4 text-cyan-500" />
                  <span className="text-sm font-medium text-cyan-400">For B.Tech Students</span>
                </div>
                <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
                  Lab Practice Platform
                </h2>
                <p className="text-lg text-[hsl(var(--bolt-text-secondary))] mb-6">
                  Master your B.Tech lab courses with interactive concepts, MCQs, and HackerRank-style coding challenges.
                </p>
                <ul className="space-y-3 mb-8">
                  {[
                    'Semester-wise lab content for all branches',
                    'Interactive concepts with video tutorials',
                    'MCQ quizzes with instant feedback',
                    'Code editor with 20+ language support',
                    'Progress tracking for students & faculty'
                  ].map((item, i) => (
                    <li key={i} className="flex items-center gap-3 text-[hsl(var(--bolt-text-secondary))]">
                      <CheckCircle className="w-5 h-5 text-cyan-500 flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
                <Link href="/lab">
                  <Button className="bg-gradient-to-r from-cyan-500 to-blue-500 hover:opacity-90">
                    Start Practicing
                    <ArrowRight className="ml-2 w-4 h-4" />
                  </Button>
                </Link>
              </div>
              <div>
                <div className="relative">
                  <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/20 to-blue-500/20 rounded-3xl blur-2xl" />
                  <div className="relative bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-2xl p-6">
                    <div className="space-y-4">
                      <div className="flex items-center justify-between p-4 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg">
                        <div className="flex items-center gap-3">
                          <div className="w-10 h-10 rounded-full bg-cyan-500/20 flex items-center justify-center">
                            <Code2 className="w-5 h-5 text-cyan-500" />
                          </div>
                          <div>
                            <p className="font-medium text-[hsl(var(--bolt-text-primary))]">Lab Practice</p>
                            <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">All B.Tech Branches</p>
                          </div>
                        </div>
                        <span className="px-3 py-1 rounded-full bg-cyan-500/20 text-cyan-400 text-sm">New</span>
                      </div>
                      <div className="grid grid-cols-3 gap-3">
                        <div className="p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg text-center">
                          <p className="text-2xl font-bold text-[hsl(var(--bolt-text-primary))]">50+</p>
                          <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">Labs</p>
                        </div>
                        <div className="p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg text-center">
                          <p className="text-2xl font-bold text-[hsl(var(--bolt-text-primary))]">1000+</p>
                          <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">MCQs</p>
                        </div>
                        <div className="p-3 bg-[hsl(var(--bolt-bg-tertiary))] rounded-lg text-center">
                          <p className="text-2xl font-bold text-[hsl(var(--bolt-text-primary))]">500+</p>
                          <p className="text-xs text-[hsl(var(--bolt-text-secondary))]">Problems</p>
                        </div>
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {['CSE', 'IT', 'ECE', 'EEE', 'ME', 'CE'].map((branch) => (
                          <span key={branch} className="px-2 py-1 bg-[hsl(var(--bolt-bg-tertiary))] text-[hsl(var(--bolt-text-secondary))] text-xs rounded">
                            {branch}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Use Cases */}
        <div className="container mx-auto px-6 py-16">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-[hsl(var(--bolt-text-primary))] mb-4">
              Who Uses BharatBuild?
            </h2>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 max-w-6xl mx-auto">
            {[
              { title: 'Students', desc: 'Complete final year projects with documentation in hours', icon: '🎓', count: '5000+' },
              { title: 'Developers', desc: 'Prototype and build production apps 10x faster', icon: '💻', count: '3000+' },
              { title: 'Startups', desc: 'Build and validate MVPs without a technical co-founder', icon: '🚀', count: '500+' },
              { title: 'Colleges', desc: 'Train students and conduct placement drives', icon: '🏛️', count: '50+' }
            ].map((item, i) => (
              <div key={i} className="bg-[hsl(var(--bolt-bg-secondary))] border border-[hsl(var(--bolt-border))] rounded-xl p-6 hover:border-[hsl(var(--bolt-accent))] transition-all text-center">
                <div className="text-4xl mb-4">{item.icon}</div>
                <h3 className="text-xl font-semibold text-[hsl(var(--bolt-text-primary))] mb-2">{item.title}</h3>
                <p className="text-sm text-[hsl(var(--bolt-text-secondary))] mb-4">{item.desc}</p>
                <div className="text-2xl font-bold bolt-gradient-text">{item.count}</div>
                <div className="text-xs text-[hsl(var(--bolt-text-secondary))]">Active Users</div>
              </div>
            ))}
          </div>
        </div>

        {/* Final CTA */}
        <div className="container mx-auto px-6 py-20">
          <div className="max-w-4xl mx-auto text-center bg-gradient-to-br from-blue-500/10 via-purple-500/10 to-cyan-500/10 border border-[hsl(var(--bolt-border))] rounded-3xl p-12">
            <h2 className="text-4xl md:text-5xl font-bold text-[hsl(var(--bolt-text-primary))] mb-6">
              Start Building Today
            </h2>
            <p className="text-xl text-[hsl(var(--bolt-text-secondary))] mb-8">
              Join thousands of developers, students, and founders building with AI
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
              <Link href="/register">
                <Button size="lg" className="bolt-gradient hover:opacity-90 transition-opacity text-lg px-8 py-6 h-auto">
                  Get Started Free
                  <ArrowRight className="ml-2 w-5 h-5" />
                </Button>
              </Link>
              <Link href="/pricing">
                <Button size="lg" variant="outline" className="text-lg px-8 py-6 h-auto border-[hsl(var(--bolt-border))] hover:border-[hsl(var(--bolt-accent))]">
                  View Pricing
                </Button>
              </Link>
            </div>
            <p className="mt-6 text-sm text-[hsl(var(--bolt-text-secondary))]">
              No credit card required • 3 free projects • Cancel anytime
            </p>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="relative z-10 border-t border-[hsl(var(--bolt-border))] mt-20">
        <div className="container mx-auto px-6 py-12">
          <div className="grid grid-cols-1 md:grid-cols-5 gap-8">
            <div className="md:col-span-2">
              <div className="flex items-center gap-2 mb-4">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-cyan-500 flex items-center justify-center">
                  <Zap className="w-5 h-5 text-white" />
                </div>
                <span className="font-bold text-lg text-[hsl(var(--bolt-text-primary))]">BharatBuild AI</span>
              </div>
              <p className="text-[hsl(var(--bolt-text-secondary))] text-sm mb-4">
                India's leading AI-powered development platform. Build full-stack apps, mobile apps, and academic projects with AI.
              </p>
              <div className="flex items-center gap-2">
                <span className="text-2xl">🇮🇳</span>
                <span className="text-sm text-[hsl(var(--bolt-text-secondary))]">Made in India</span>
              </div>
            </div>

            <div>
              <h4 className="font-semibold text-[hsl(var(--bolt-text-primary))] mb-4">Product</h4>
              <ul className="space-y-2 text-[hsl(var(--bolt-text-secondary))] text-sm">
                <li><Link href="/build" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Build App</Link></li>
                <li><Link href="/projects" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">My Projects</Link></li>
                <li><Link href="/paper" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Research Paper</Link></li>
                <li><Link href="/pricing" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Pricing</Link></li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold text-[hsl(var(--bolt-text-primary))] mb-4">Tools</h4>
              <ul className="space-y-2 text-[hsl(var(--bolt-text-secondary))] text-sm">
                <li><Link href="/import" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Import Project</Link></li>
                <li><Link href="/campus-drive" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Campus Drive</Link></li>
                <li><Link href="/lab" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Lab Practice</Link></li>
                <li><Link href="/adventure" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Adventure Mode</Link></li>
              </ul>
            </div>

            <div>
              <h4 className="font-semibold text-[hsl(var(--bolt-text-primary))] mb-4">Legal</h4>
              <ul className="space-y-2 text-[hsl(var(--bolt-text-secondary))] text-sm">
                <li><Link href="/privacy" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Privacy Policy</Link></li>
                <li><Link href="/terms" className="hover:text-[hsl(var(--bolt-text-primary))] transition-colors">Terms of Service</Link></li>
              </ul>
            </div>
          </div>

          <div className="border-t border-[hsl(var(--bolt-border))] mt-12 pt-8 text-center text-[hsl(var(--bolt-text-secondary))] text-sm">
            © 2025 BharatBuild AI. All rights reserved. Built with ❤️ in India
          </div>
        </div>
      </footer>
    </div>
  )
}
