# Re-export all models for convenient imports
from app.models.user import User, UserRole
from app.models.project import Project, ProjectStatus
from app.models.file_version import ProjectFileVersion
from app.models.project_file import ProjectFile, FileGenerationStatus
from app.models.document import Document
from app.models.billing import Plan, Subscription, SubscriptionStatus, Transaction, PlanType
from app.models.usage import UsageLog, TokenUsage, TokenUsageLog, AgentType, OperationType
from app.models.api_key import APIKey, APIKeyStatus
from app.models.audit_log import AuditLog
from app.models.system_setting import SystemSetting
from app.models.workspace import Workspace
from app.models.token_balance import TokenBalance, TokenTransaction, TokenPurchase
from app.models.sandbox import SandboxInstance, SandboxStatus
from app.models.session import Session
from app.models.snapshot import Snapshot
from app.models.agent_task import AgentTask
from app.models.project_message import ProjectMessage
from app.models.workshop_enrollment import WorkshopEnrollment
from app.models.campus_drive import (
    CampusDrive,
    CampusDriveRegistration,
    CampusDriveQuestion,
    CampusDriveResponse,
    QuestionCategory,
    QuestionDifficulty,
    RegistrationStatus,
)
from app.models.coupon import (
    Coupon,
    CouponUsage,
    CouponCategory,
    CouponStatus,
    Wallet,
    WalletTransaction,
    WalletTransactionType,
    WalletTransactionSource,
)
from app.models.criterion1 import (
    CurriculumFeedback,
    CurriculumEvidence,
    IndustryPartner,
    AdvisoryBoardMeeting,
    ValueAddedCourse,
    ValueAddedCourseEnrollment,
    InternshipRecord,
    FeedbackType,
    FeedbackStatus,
    EvidenceType,
    PartnerType,
    MoUStatus,
    CourseType,
    CourseMode,
    InternshipType,
    InternshipStatus,
)
from app.models.criterion2 import (
    LMSAdoption,
    LessonPlan,
    AttendanceRecord,
    CIERecord,
    EvaluationRubric,
    StudentPerformance,
    TeacherProfile,
    DigitalContent,
    LearningOutcomeAttainment,
    BlendedLearningSession,
    LMSPlatform,
    BloomsLevel,
    AttendanceStatus,
    AssessmentType,
    TeachingMethod,
    ContentType,
    TeacherDesignation,
    PerformanceLevel,
)
from app.models.criterion3 import (
    ResearchProject,
    Publication,
    Patent,
    Startup,
    InnovationCell,
    Hackathon,
    ExtensionActivity,
    Consultancy,
    ResearchFunding,
    ProjectType,
    ProjectStatus as ResearchProjectStatus,
    PublicationType,
    PublicationIndexing,
    PatentStatus,
    PatentType,
    StartupStage,
    StartupStatus,
    EventType,
    ExtensionType,
    FundingAgency,
)
from app.models.criterion4 import (
    Infrastructure,
    LabEquipment,
    SoftwareLicense,
    LibraryResource,
    LabUtilization,
    MaintenanceRecord,
    EResourceAccess,
    InfrastructureType,
    EquipmentStatus,
    LicenseType,
    ResourceType,
    MaintenanceType,
)
from app.models.criterion5 import (
    Scholarship,
    PlacementRecord,
    CareerCounseling,
    StudentGrievance,
    AlumniRecord,
    StudentMentoring,
    CompetitiveExam,
    ScholarshipType,
    PlacementStatus,
    CompanyType,
    GrievanceCategory,
    GrievanceStatus,
    AlumniStatus,
)
from app.models.criterion6 import (
    InstitutionalGovernance,
    GovernanceMeeting,
    InstitutionalPolicy,
    IQACActivity,
    FacultyDevelopment,
    FinancialAudit,
    StrategicPlan,
    MeetingType,
    PolicyType,
    QualityInitiativeType,
    FDPType,
    AuditType,
)
from app.models.criterion7 import (
    GenderEquityProgram,
    GreenInitiative,
    InclusivityProgram,
    EthicsProgram,
    BestPractice,
    InstitutionalDistinctiveness,
    InstitutionalAward,
    GreenInitiativeType,
    InclusivityType,
    EthicsType,
    BestPracticeCategory,
    AwardCategory,
)
from app.models.nba import (
    ProgramVisionMission,
    ProgramOutcome,
    CourseOutcome,
    COAttainment,
    POAttainment,
    StudentResultAnalysis,
    NBAContinuousImprovement,
    NBAFacultyContribution,
    NBALabFacility,
    ProgramType,
    AttainmentLevel,
    AssessmentMethod,
    FeedbackSource,
    ActionStatus,
)
from app.models.naac_rbac import (
    NAACRole,
    UserNAACRole,
    NAACPermission,
    RolePermission,
    NAACTask,
    NAACTaskComment,
    NAACApprovalWorkflow,
    NAACNotification,
    NAACRoleType,
    NAACPermissionType,
    ApprovalStatus,
    TaskStatus,
    TaskPriority,
    NotificationType,
)
from app.models.college_onboarding import (
    CollegeProfile,
    CollegeDepartment,
    CollegeProgram,
    CollegeInvitation,
    OnboardingProgress,
    CollegeType,
    AccreditationStatus,
    SubscriptionPlan as CollegeSubscriptionPlan,
    OnboardingStep,
    InvitationStatus,
)

__all__ = [
    # User
    "User",
    "UserRole",
    # Project
    "Project",
    "ProjectStatus",
    "ProjectFile",
    "ProjectFileVersion",
    "FileGenerationStatus",
    "ProjectMessage",
    # Documents
    "Document",
    # Billing
    "Plan",
    "PlanType",
    "Subscription",
    "SubscriptionStatus",
    "Transaction",
    # Usage
    "UsageLog",
    "TokenUsage",
    "TokenUsageLog",
    "AgentType",
    "OperationType",
    # API Keys
    "APIKey",
    "APIKeyStatus",
    # Admin
    "AuditLog",
    "SystemSetting",
    # Workspace
    "Workspace",
    # Tokens
    "TokenBalance",
    "TokenTransaction",
    "TokenPurchase",
    # Sandbox
    "SandboxInstance",
    "SandboxStatus",
    # Session
    "Session",
    # Snapshot
    "Snapshot",
    # Agent
    "AgentTask",
    # Workshop
    "WorkshopEnrollment",
    # Campus Drive
    "CampusDrive",
    "CampusDriveRegistration",
    "CampusDriveQuestion",
    "CampusDriveResponse",
    "QuestionCategory",
    "QuestionDifficulty",
    "RegistrationStatus",
    # Coupon & Wallet
    "Coupon",
    "CouponUsage",
    "CouponCategory",
    "CouponStatus",
    "Wallet",
    "WalletTransaction",
    "WalletTransactionType",
    "WalletTransactionSource",
    # NAAC Criterion 1
    "CurriculumFeedback",
    "CurriculumEvidence",
    "IndustryPartner",
    "AdvisoryBoardMeeting",
    "ValueAddedCourse",
    "ValueAddedCourseEnrollment",
    "InternshipRecord",
    "FeedbackType",
    "FeedbackStatus",
    "EvidenceType",
    "PartnerType",
    "MoUStatus",
    "CourseType",
    "CourseMode",
    "InternshipType",
    "InternshipStatus",
    # NAAC Criterion 2
    "LMSAdoption",
    "LessonPlan",
    "AttendanceRecord",
    "CIERecord",
    "EvaluationRubric",
    "StudentPerformance",
    "TeacherProfile",
    "DigitalContent",
    "LearningOutcomeAttainment",
    "BlendedLearningSession",
    "LMSPlatform",
    "BloomsLevel",
    "AttendanceStatus",
    "AssessmentType",
    "TeachingMethod",
    "ContentType",
    "TeacherDesignation",
    "PerformanceLevel",
    # NAAC Criterion 3
    "ResearchProject",
    "Publication",
    "Patent",
    "Startup",
    "InnovationCell",
    "Hackathon",
    "ExtensionActivity",
    "Consultancy",
    "ResearchFunding",
    "ProjectType",
    "ResearchProjectStatus",
    "PublicationType",
    "PublicationIndexing",
    "PatentStatus",
    "PatentType",
    "StartupStage",
    "StartupStatus",
    "EventType",
    "ExtensionType",
    "FundingAgency",
    # NAAC Criterion 4
    "Infrastructure",
    "LabEquipment",
    "SoftwareLicense",
    "LibraryResource",
    "LabUtilization",
    "MaintenanceRecord",
    "EResourceAccess",
    "InfrastructureType",
    "EquipmentStatus",
    "LicenseType",
    "ResourceType",
    "MaintenanceType",
    # NAAC Criterion 5
    "Scholarship",
    "PlacementRecord",
    "CareerCounseling",
    "StudentGrievance",
    "AlumniRecord",
    "StudentMentoring",
    "CompetitiveExam",
    "ScholarshipType",
    "PlacementStatus",
    "CompanyType",
    "GrievanceCategory",
    "GrievanceStatus",
    "AlumniStatus",
    # NAAC Criterion 6
    "InstitutionalGovernance",
    "GovernanceMeeting",
    "InstitutionalPolicy",
    "IQACActivity",
    "FacultyDevelopment",
    "FinancialAudit",
    "StrategicPlan",
    "MeetingType",
    "PolicyType",
    "QualityInitiativeType",
    "FDPType",
    "AuditType",
    # NAAC Criterion 7
    "GenderEquityProgram",
    "GreenInitiative",
    "InclusivityProgram",
    "EthicsProgram",
    "BestPractice",
    "InstitutionalDistinctiveness",
    "InstitutionalAward",
    "GreenInitiativeType",
    "InclusivityType",
    "EthicsType",
    "BestPracticeCategory",
    "AwardCategory",
    # NBA Accreditation
    "ProgramVisionMission",
    "ProgramOutcome",
    "CourseOutcome",
    "COAttainment",
    "POAttainment",
    "StudentResultAnalysis",
    "NBAContinuousImprovement",
    "NBAFacultyContribution",
    "NBALabFacility",
    "ProgramType",
    "AttainmentLevel",
    "AssessmentMethod",
    "FeedbackSource",
    "ActionStatus",
    # NAAC RBAC
    "NAACRole",
    "UserNAACRole",
    "NAACPermission",
    "RolePermission",
    "NAACTask",
    "NAACTaskComment",
    "NAACApprovalWorkflow",
    "NAACNotification",
    "NAACRoleType",
    "NAACPermissionType",
    "ApprovalStatus",
    "TaskStatus",
    "TaskPriority",
    "NotificationType",
    # College Onboarding
    "CollegeProfile",
    "CollegeDepartment",
    "CollegeProgram",
    "CollegeInvitation",
    "OnboardingProgress",
    "CollegeType",
    "AccreditationStatus",
    "CollegeSubscriptionPlan",
    "OnboardingStep",
    "InvitationStatus",
]
