"""add_missing_project_columns

Revision ID: 22b8a8e697ea
Revises: 
Create Date: 2025-12-02 17:35:30.749908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22b8a8e697ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed drop_table operations for token_balances, token_purchases, token_transactions
    # to preserve existing data. These tables exist in the database but may not be in current models.

    # Add missing columns to projects table
    op.add_column('projects', sa.Column('s3_path', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('s3_zip_key', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('plan_json', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('file_index', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('history', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('technology', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('is_saved', sa.Boolean(), nullable=True, server_default='false'))
    op.add_column('projects', sa.Column('last_activity', sa.DateTime(), nullable=True))

    # Add indexes for projects table using raw SQL with IF NOT EXISTS
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_created_at ON projects (created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_status ON projects (status)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_user_id ON projects (user_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_user_status ON projects (user_id, status)')

    # Add indexes for project_files table using raw SQL with IF NOT EXISTS
    op.execute('CREATE INDEX IF NOT EXISTS ix_project_files_content_hash ON project_files (content_hash)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_project_files_path ON project_files (path)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_project_files_project_id ON project_files (project_id)')
    op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_project_files_project_path ON project_files (project_id, path)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes for projects table
    op.execute('DROP INDEX IF EXISTS ix_projects_user_status')
    op.execute('DROP INDEX IF EXISTS ix_projects_user_id')
    op.execute('DROP INDEX IF EXISTS ix_projects_status')
    op.execute('DROP INDEX IF EXISTS ix_projects_created_at')

    # Drop columns from projects table
    op.drop_column('projects', 'last_activity')
    op.drop_column('projects', 'is_saved')
    op.drop_column('projects', 'technology')
    op.drop_column('projects', 'history')
    op.drop_column('projects', 'file_index')
    op.drop_column('projects', 'plan_json')
    op.drop_column('projects', 's3_zip_key')
    op.drop_column('projects', 's3_path')

    # Drop indexes for project_files table
    op.execute('DROP INDEX IF EXISTS ix_project_files_project_path')
    op.execute('DROP INDEX IF EXISTS ix_project_files_project_id')
    op.execute('DROP INDEX IF EXISTS ix_project_files_path')
    op.execute('DROP INDEX IF EXISTS ix_project_files_content_hash')
    # ### end Alembic commands ###
