"""add_missing_project_columns

Revision ID: 22b8a8e697ea
Revises: 
Create Date: 2025-12-02 17:35:30.749908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22b8a8e697ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration is idempotent - it checks if tables/columns exist before adding them.
    # This allows init_tables (SQLAlchemy create_all) to run first without conflicts.

    conn = op.get_bind()

    # Check if projects table exists
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'projects')"
    ))
    projects_exists = result.scalar()

    if not projects_exists:
        # Table doesn't exist - skip column additions (init_tables should create it)
        print("Projects table does not exist, skipping column additions")
        return

    # Get existing columns in projects table
    result = conn.execute(sa.text(
        "SELECT column_name FROM information_schema.columns WHERE table_name = 'projects'"
    ))
    existing_columns = {row[0] for row in result}

    # Add columns only if they don't exist
    columns_to_add = [
        ('s3_path', sa.Column('s3_path', sa.String(length=500), nullable=True)),
        ('s3_zip_key', sa.Column('s3_zip_key', sa.String(length=500), nullable=True)),
        ('plan_json', sa.Column('plan_json', sa.JSON(), nullable=True)),
        ('file_index', sa.Column('file_index', sa.JSON(), nullable=True)),
        ('history', sa.Column('history', sa.JSON(), nullable=True)),
        ('technology', sa.Column('technology', sa.String(length=255), nullable=True)),
        ('is_saved', sa.Column('is_saved', sa.Boolean(), nullable=True, server_default='false')),
        ('last_activity', sa.Column('last_activity', sa.DateTime(), nullable=True)),
    ]

    for col_name, col_def in columns_to_add:
        if col_name not in existing_columns:
            op.add_column('projects', col_def)
            print(f"Added column: {col_name}")
        else:
            print(f"Column already exists: {col_name}")

    # Add indexes using IF NOT EXISTS (already idempotent)
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_created_at ON projects (created_at)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_status ON projects (status)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_user_id ON projects (user_id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_user_status ON projects (user_id, status)')

    # Check if project_files table exists before adding indexes
    result = conn.execute(sa.text(
        "SELECT EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'project_files')"
    ))
    project_files_exists = result.scalar()

    if project_files_exists:
        op.execute('CREATE INDEX IF NOT EXISTS ix_project_files_content_hash ON project_files (content_hash)')
        op.execute('CREATE INDEX IF NOT EXISTS ix_project_files_path ON project_files (path)')
        op.execute('CREATE INDEX IF NOT EXISTS ix_project_files_project_id ON project_files (project_id)')
        op.execute('CREATE UNIQUE INDEX IF NOT EXISTS ix_project_files_project_path ON project_files (project_id, path)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes for projects table
    op.execute('DROP INDEX IF EXISTS ix_projects_user_status')
    op.execute('DROP INDEX IF EXISTS ix_projects_user_id')
    op.execute('DROP INDEX IF EXISTS ix_projects_status')
    op.execute('DROP INDEX IF EXISTS ix_projects_created_at')

    # Drop columns from projects table
    op.drop_column('projects', 'last_activity')
    op.drop_column('projects', 'is_saved')
    op.drop_column('projects', 'technology')
    op.drop_column('projects', 'history')
    op.drop_column('projects', 'file_index')
    op.drop_column('projects', 'plan_json')
    op.drop_column('projects', 's3_zip_key')
    op.drop_column('projects', 's3_path')

    # Drop indexes for project_files table
    op.execute('DROP INDEX IF EXISTS ix_project_files_project_path')
    op.execute('DROP INDEX IF EXISTS ix_project_files_project_id')
    op.execute('DROP INDEX IF EXISTS ix_project_files_path')
    op.execute('DROP INDEX IF EXISTS ix_project_files_content_hash')
    # ### end Alembic commands ###
