# Pydantic schemas
from app.schemas.campus_drive import (
    CampusDriveCreate,
    CampusDriveUpdate,
    CampusDriveResponse,
    StudentRegistrationCreate,
    RegistrationResponse,
    QuestionCreate,
    QuestionResponse,
    QuestionForQuiz,
    QuizStartResponse,
    QuizSubmission,
    QuizResultResponse,
    CampusDriveStats,
)
from app.schemas.coupon import (
    CouponCreate,
    CouponUpdate,
    CouponResponse,
    CouponListResponse,
    CouponValidateRequest,
    CouponValidateResponse,
    CouponApplyRequest,
    CouponApplyResponse,
    CouponUsageResponse,
    CouponUsageListResponse,
    WalletResponse,
    WalletTransactionResponse,
    WalletTransactionListResponse,
    MyCouponResponse,
    CouponAnalytics,
    CouponStatsResponse,
)
