"""
GitHub Integration for BharatBuild MCP Client

Creates repositories and pushes project files via GitHub API.
"""

import base64
import logging
from typing import Dict, Any, List, Optional
from pathlib import Path

import httpx

logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"


class GitHubIntegration:
    """Push BharatBuild projects to GitHub"""
    
    def __init__(self, token: str):
        self.token = token
        self.headers = {
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
    
    async def create_and_push(
        self,
        project_id: str,
        user_id: str,
        repo_name: str,
        is_private: bool = False,
        description: str = "Generated by BharatBuild AI"
    ) -> Dict[str, Any]:
        """
        Create a GitHub repo and push all project files.
        
        Args:
            project_id: BharatBuild project ID
            user_id: User ID (to find files on disk)
            repo_name: Repository name
            is_private: Private repo
            description: Repo description
            
        Returns:
            {"success": True, "repo_url": "https://github.com/user/repo"}
        """
        async with httpx.AsyncClient(timeout=30.0) as client:
            # Step 1: Get authenticated user
            user_resp = await client.get(f"{GITHUB_API}/user", headers=self.headers)
            if user_resp.status_code != 200:
                return {"success": False, "error": f"GitHub auth failed: {user_resp.status_code}"}
            
            github_username = user_resp.json()["login"]
            
            # Step 2: Create repository
            create_resp = await client.post(
                f"{GITHUB_API}/user/repos",
                headers=self.headers,
                json={
                    "name": repo_name,
                    "description": description,
                    "private": is_private,
                    "auto_init": False  # We'll push files ourselves
                }
            )
            
            if create_resp.status_code == 422:
                # Repo might already exist
                logger.warning(f"[GitHub] Repo {repo_name} might already exist, trying to use it")
            elif create_resp.status_code not in (201, 200):
                return {"success": False, "error": f"Failed to create repo: {create_resp.text[:200]}"}
            
            repo_url = f"https://github.com/{github_username}/{repo_name}"
            
            # Step 3: Get project files from disk
            from app.services.unified_storage import unified_storage
            sandbox_path = unified_storage.get_sandbox_path(project_id, user_id)
            
            if not sandbox_path.exists():
                return {"success": False, "error": "Project files not found on disk"}
            
            # Step 4: Push files using Git Trees API (batch push)
            files_to_push = await self._collect_files(sandbox_path)
            
            if not files_to_push:
                return {"success": False, "error": "No files found to push"}
            
            # Create blobs for each file
            tree_items = []
            for file_path, content in files_to_push:
                # Create blob
                blob_resp = await client.post(
                    f"{GITHUB_API}/repos/{github_username}/{repo_name}/git/blobs",
                    headers=self.headers,
                    json={
                        "content": base64.b64encode(content.encode('utf-8')).decode('utf-8'),
                        "encoding": "base64"
                    }
                )
                
                if blob_resp.status_code != 201:
                    logger.warning(f"[GitHub] Failed to create blob for {file_path}")
                    continue
                
                tree_items.append({
                    "path": file_path,
                    "mode": "100644",
                    "type": "blob",
                    "sha": blob_resp.json()["sha"]
                })
            
            if not tree_items:
                return {"success": False, "error": "Failed to create file blobs"}
            
            # Create tree
            tree_resp = await client.post(
                f"{GITHUB_API}/repos/{github_username}/{repo_name}/git/trees",
                headers=self.headers,
                json={"tree": tree_items}
            )
            
            if tree_resp.status_code != 201:
                return {"success": False, "error": f"Failed to create tree: {tree_resp.text[:200]}"}
            
            tree_sha = tree_resp.json()["sha"]
            
            # Create commit
            commit_resp = await client.post(
                f"{GITHUB_API}/repos/{github_username}/{repo_name}/git/commits",
                headers=self.headers,
                json={
                    "message": "Initial commit - Generated by BharatBuild AI",
                    "tree": tree_sha
                }
            )
            
            if commit_resp.status_code != 201:
                return {"success": False, "error": f"Failed to create commit: {commit_resp.text[:200]}"}
            
            commit_sha = commit_resp.json()["sha"]
            
            # Update main branch reference
            ref_resp = await client.post(
                f"{GITHUB_API}/repos/{github_username}/{repo_name}/git/refs",
                headers=self.headers,
                json={
                    "ref": "refs/heads/main",
                    "sha": commit_sha
                }
            )
            
            if ref_resp.status_code not in (201, 200):
                # Try updating existing ref
                ref_resp = await client.patch(
                    f"{GITHUB_API}/repos/{github_username}/{repo_name}/git/refs/heads/main",
                    headers=self.headers,
                    json={"sha": commit_sha, "force": True}
                )
            
            logger.info(f"[GitHub] Successfully pushed {len(tree_items)} files to {repo_url}")
            
            return {
                "success": True,
                "repo_url": repo_url,
                "files_pushed": len(tree_items),
                "commit_sha": commit_sha
            }
    
    async def _collect_files(self, project_path: Path) -> List[tuple]:
        """Collect all project files (excluding node_modules, .git, etc.)"""
        files = []
        skip_dirs = {'node_modules', '.git', 'dist', 'build', '__pycache__', '.next', 'venv', '.venv'}
        skip_files = {'.DS_Store', 'Thumbs.db', '.project_metadata.json'}
        
        for item in project_path.rglob('*'):
            if item.is_file():
                # Skip unwanted directories
                if any(skip in item.parts for skip in skip_dirs):
                    continue
                # Skip unwanted files
                if item.name in skip_files:
                    continue
                # Skip large files (>1MB)
                if item.stat().st_size > 1_000_000:
                    continue
                
                try:
                    relative_path = str(item.relative_to(project_path)).replace('\\', '/')
                    content = item.read_text(encoding='utf-8', errors='ignore')
                    files.append((relative_path, content))
                except Exception as e:
                    logger.warning(f"[GitHub] Skipping file {item}: {e}")
        
        return files
