import fs from "fs";
import path from "path";

function hookScript(event: string): string {
  return `#!/bin/sh
# BharatBuild git hook — ${event}
# Auto-generated by: bharatbuild hooks install-git
ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")
if command -v bharatbuild > /dev/null 2>&1; then
  bharatbuild hook:run ${event} "$@"
elif [ -f "$ROOT/node_modules/.bin/bharatbuild" ]; then
  "$ROOT/node_modules/.bin/bharatbuild" hook:run ${event} "$@"
fi
`;
}

export function installGitHooks(dir?: string): void {
  const root = dir ?? process.cwd();
  const hooksDir = path.join(root, ".git", "hooks");
  if (!fs.existsSync(hooksDir)) {
    console.warn("  ⚠  No .git/hooks directory found. Run inside a git repo.");
    return;
  }
  const hookMap: Array<[string, string]> = [
    ["pre-commit",  "git-commit"],
    ["post-commit", "git-commit"],
    ["pre-push",    "git-push"],
  ];
  for (const [gitHook, event] of hookMap) {
    const p = path.join(hooksDir, gitHook);
    fs.writeFileSync(p, hookScript(event), { mode: 0o755 });
    console.log(`  ✓ Installed git hook: ${gitHook} → bharatbuild hook:run ${event}`);
  }
}

export function uninstallGitHooks(dir?: string): void {
  const root = dir ?? process.cwd();
  const hooksDir = path.join(root, ".git", "hooks");
  for (const gitHook of ["pre-commit", "post-commit", "pre-push"]) {
    const p = path.join(hooksDir, gitHook);
    try {
      if (fs.existsSync(p)) {
        const content = fs.readFileSync(p, "utf8");
        if (content.includes("BharatBuild git hook")) {
          fs.unlinkSync(p);
          console.log(`  ✓ Removed git hook: ${gitHook}`);
        }
      }
    } catch {}
  }
}
